// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shake_internal
Rcpp::List shake_internal(Rcpp::List& graph, Rcpp::IntegerVector size, Rcpp::IntegerVector permutations, Rcpp::IntegerVector hard_stop);
RcppExport SEXP _ppitools_shake_internal(SEXP graphSEXP, SEXP sizeSEXP, SEXP permutationsSEXP, SEXP hard_stopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type graph(graphSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hard_stop(hard_stopSEXP);
    rcpp_result_gen = Rcpp::wrap(shake_internal(graph, size, permutations, hard_stop));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ppitools_shake_internal", (DL_FUNC) &_ppitools_shake_internal, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppitools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
