# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shake_internal <- function(graph, size, permutations, hard_stop) {
    .Call('_ppitools_shake_internal', PACKAGE = 'ppitools', graph, size, permutations, hard_stop)
}

